cache: packages
sudo: required
warnings_are_errors: false
services:
  - docker
# database setup
before_install:
  # Set up environment and create required images
  # If no error don't print output
  - docker-compose ps
script:
  # Load packages and install the required packages
  # Install retriever from source and run tests
  - docker-compose  run rdata /bin/sh -c 'Rscript load_and_test.R'
  - docker-compose run rdata /bin/sh -c 'R CMD build . --no-build-vignettes && R CMD check *tar.gz --no-install --no-multiarch --no-examples --no-manual'
